### ISSUE TITLE
Add home tab screen with ability to filter articles

### ISSUE THREAD

**Issue by audip** [audip/refined-hckrnews#1]
When the user launches the app, it will open the `Home Tab` screen with a [segmented control](https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/) based bar for `Home`, `Top 10`, `Top 20`, `Top 50%` articles that can be filtered. 

**Tasks:**
- [ ] Create a `Home` [tab bar](https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/) screen
- [ ] Create a segmented control for `Home`, `Top 10`, `Top 20` and `Top 50%` controls similar to [Hckrnews](http://hckrnews.com)
- [ ] Fetch articles from [HnRSS API](https://edavis.github.io/hnrss) or [HackerNews API](https://github.com/HackerNews/API) on a click of segmented control menu 
- [ ] Save and remember the segmented control tab for next launch of the app

**Resources:**
Home tab screen from [Screen Mockup](https://github.com/audip/refined-hckrnews/blob/master/docs/ScreenMockups.jpg)
