### ISSUE TITLE
Add story detail screen to view comments and link to article

### ISSUE THREAD

**Issue by audip** [audip/refined-hckrnews#2]
When the user clicks on the article table cell, it will open the `Story Detail` screen with a link to the article and table view of threaded comments. 

**Tasks:**
- [ ] Create a `Story Detail` screen with Back button to previous tab, with a picture (favicon), article link and comments 
- [ ] Add ability to view/read webpages without leaving the app, similar to this on [iOS](https://www.simplifiedios.net/uiwebview-example-load-url/) or [Android](https://javapapers.com/android/how-to-build-android-in-app-browser-with-webview/)
- [ ] Fetch articles and comments from [HnRSS API](https://edavis.github.io/hnrss) or [HackerNews API](https://github.com/HackerNews/API) on a click of a story.

**Resources:**
Story Detail screen from [Screen Mockup](https://github.com/audip/refined-hckrnews/blob/master/docs/ScreenMockups.jpg)
