### ISSUE TITLE
Add settings tab screen with basic settings

### ISSUE THREAD

**Issue by audip** [audip/refined-hckrnews#3]
When the user selects the `Settings` tab, it will open the `Settings Tab` screen with basic settings functionality. 

**Tasks:**
- [ ] Create a `Settings` [tab bar](https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/) screen
- [ ] Add an option for modify appearance such as font face, text size, [iOS reader mode](http://osxdaily.com/2019/03/28/enable-safari-reader-view-automatically-ios/))
- [ ] Add an option to modify theme (light mode / gray mode / OLED dark mode), similar to [Twitter mobile app](https://9to5mac.com/2019/03/28/twitter-black-dark-mode-option/)
- [ ] Add an option to pick an app icon from available custom icons (light, dark, colorful and seasonal icons)

**Resources:**
Settings tab screen from [Screen Mockup](https://github.com/audip/refined-hckrnews/blob/master/docs/ScreenMockups.jpg)
